ckeditor/ckeditor5-link

src/link.js, tests/link.js
Fixes #24 
Depends on: https://github.com/ckeditor/ckeditor5-ui-default/pull/69
=> Selected input value when balloon panel is opened.

src/link.js, src/ui/linkballoonpanel.js, src/ui/linkballoonpanelview.js, tests/link.js, tests/manual/link.js, tests/ui/linkballoonpanel.js
I'm not proud of it, but this PR fixes few issues #20 #21 #26. Thy were strongly connected.
Related: https://github.com/ckeditor/ckeditor5-ui-default/issues/77
=> Improved opening and closing balloon panel

src/link.js, src/unlinkcommand.js, tests/link.js, tests/unlinkcommand.js
=> Changed the way of checking of linkCommand is enabled.

src/link.js, tests/link.js
=> Changed link keystroke to Ctrl+K.

src/link.js, tests/link.js
Fixes: #40 
This PRs have to be merged before:
- https://github.com/ckeditor/ckeditor5-ui-default/issues/85
- https://github.com/ckeditor/ckeditor5-ui-default/issues/87
Blocked by (failing tests):
- https://github.com/ckeditor/ckeditor5-ui/issues/83
=> Helpers for closing link balloon panel.

tests/ui/linkballoonpanel.js
=> Changed test to be more browser independent.

src/link.js, tests/link.js
Fixes #50 
Depends on: https://github.com/ckeditor/ckeditor5-ui/issues/73
=> Refactored Link feature after removing view#model.

src/link.js, src/ui/linkballoonpanel.js, tests/link.js
=> Added LinkBalloonPanelView#element to FocusTracker.

src/ui/linkformview.js
Closes #61.
Requires https://github.com/ckeditor/ckeditor5-ui/pull/109.
=> t/61: Used view.addChildren() instead of view.addChild().

src/ui/linkformview.js
=> t/63: MVC refactoring followups

src/link.js, tests/link.js
=> t/65b: Saving the new url does not update the link in editable.

src/link.js
Requires https://github.com/ckeditor/ckeditor5-ui-default/issues/120.
Closes #68.
=> Simplify the usage of UI bindings/handlers.

src/link.js, tests/link.js
Requires https://github.com/ckeditor/ckeditor5-ui-default/pull/134.
Closes #75.
=> Aligned link to the new BalloonPanelView API.

src/link.js, src/ui/linkformview.js, tests/link.js, tests/ui/linkformview.js
Requires https://github.com/ckeditor/ckeditor5-core/pull/61.
Closes #79.
=> t/79: Controlled keyboard navigation in the link UI (LinkFormView)

src/link.js, src/ui/linkformview.js, tests/link.js
Other: Fixed paths after refactoring in ckeditor5-ui. Closes #83.
=> Fixed paths after refactoring in ckeditor5-ui.

src/link.js, tests/link.js
Feature: Integrated link UI with editor ContextualBalloon. Closes #91.
---
Depends on: ckeditor/ckeditor5-ui#177
=> Integrated link UI with editor ContextualBalloon.

src/link.js, tests/link.js
Other: Aligned Link to the latest ContextualBalloon API. Closes #103.
---
Needs: https://github.com/ckeditor/ckeditor5-ui/pull/201
=> Other: Aligned Link to the latest ContextualBalloon API

tests/link.js
Other: Aligned tests to the latest ContextuaBalloon plugin API. Closes #101.
---
Requires: https://github.com/ckeditor/ckeditor5-ui/pull/196
=> Aligned tests to the latest ContextualBalloon API.

tests/link.js
Other: Added test case checking `Link` plugin and `ui.focusTracker` integration. Closes #106.
=> Added test case checking link and focus tracker integration.

src/linkengine.js, tests/linkengine.js
Fix: Link should have higher priority than all other attribute elements. Closes #121.
=> t/121: Link should have higher priority than all other attribute elements

src/linkengine.js, tests/linkengine.js
Other: Aligning with new conversion helpers API.
---
=> Other: Aligning with new conversion helpers API

src/linkediting.js, tests/linkediting.js, tests/linkui.js, tests/manual/linkhighlight.html, tests/manual/linkhighlight.js, tests/manual/linkhighlight.md, theme/link.css
Feature: Added highlight to link with selection inside. Closes #72.
---
Branches to merge together with this PR:
* ckeditor5-typing: [t/ckeditor5-link/72](https://github.com/ckeditor/ckeditor5-typing/tree/t/ckeditor5-link/72)
* ckeditor5-theme-lark: [t/ckeditor5-link/72](https://github.com/ckeditor/ckeditor5-theme-lark/tree/t/ckeditor5-link/72)
=> Add link highlighting 

src/utils.js
Other: Aligned to changes in ckeditor5-engine.
=> Other: Aligned to changes in ckeditor5-engine

src/linkediting.js
Internal: Aligned to the changes in the engine. See ckeditor/ckeditor5#742.
Requires: https://github.com/ckeditor/ckeditor5-engine/pull/1389.
=> Aligned to the changes in engine

src/linkui.js, tests/linkui.js
Internal: Used UI#update event instead of View#render to attach the UI components.
---
- https://github.com/ckeditor/ckeditor5-core/pull/131
=> Used UI#update event instead of View#render to attach the UI components.

tests/utils.js
Internal: Adjusted code to `Writer` to `DowncastWriter` rename in `ckeditor5-engine`.
---
See https://github.com/ckeditor/ckeditor5-engine/issues/1515.
=> Adjusted code to 'Writer' to 'DowncastWriter' rename in 'ckeditor5-engine'

src/linkui.js, tests/linkui.js
Feature: Link icon will be active when the selection is placed inside the link. Closes #173.
=> Link icon interacts with the selection

theme/linkactions.css, theme/linkform.css
Feature: Improved responsiveness of the form and actions views in narrow viewports (see ckeditor/ckeditor5#416).
---
A part of https://github.com/ckeditor/ckeditor5/pull/1299.
=> t/ckeditor5/416: Improved responsiveness of the form and actions views

src/linkui.js, tests/linkui.js
Internal: Aligned code to the latest `ContextualBalloon` API. Part of https://github.com/ckeditor/ckeditor5-ui/issues/491.
---
=> Changes according to new ContextualBallon panels API.

src/linkui.js, tests/linkui.js
Internal: Made sure link balloon will be visible after pressing Ctrl+K. Closes #227.
---
=> Made sure link balloon will be visible after pressing Ctrl+K.

tests/linkediting.js
Tests: Return editor promise from asynchronous tests.
---
* Sub-PR for: https://github.com/ckeditor/ckeditor5-image/pull/325
=> Return editor promise from asynchronous tests.

tests/linkui.js
Tests: Fixed tests leaking editor instances / DOM elements. See ckeditor/ckeditor5#6002.
---
For a complete list of PRs see https://github.com/ckeditor/ckeditor5/issues/6002#issuecomment-567834563.
=> Fixed tests leaking editor instance / DOM element.
