src/link.js, tests/link.js
Requires https://github.com/ckeditor/ckeditor5-editor-classic/pull/39.
Closes #70.
=> t/70: Updated link after focusTracker moved from editor to editor.ui.

src/ui/linkformview.js, tests/ui/linkformview.js
Requires https://github.com/ckeditor/ckeditor5-ui/pull/147.
Closes #81.
=> t/81: Removed obsolete View.addChildren() calls from LinkFormView.

src/link.js, tests/link.js
Feature: Made Link Plugins `#showPanel()` and `#hidePanel()` methods protected. Closes #95. Closes #94.
---
It makes possible to fully test these methods and then test how link uses them without a need to execute them.
=> Made showPanel() and hidePanel() protected

src/link.js, tests/link.js
Fix: Improved focus management test. Closes #95.
---
Needs: https://github.com/ckeditor/ckeditor5-ui/pull/194
=> Improved focus management test.

src/linkengine.js, tests/linkengine.js
Fix: Schema is now correctly set for Link feature. Closes #97.
=> Fixed `Schema#allow()` entry.

src/link.js, tests/link.js
Fix: Link balloon should hide unlink button when creating a link. Closes #53.
---
Requires https://github.com/ckeditor/ckeditor5-ui/pull/210.
=> t/53: Link balloon should hide unlink button when creating a link

src/ui/linkformview.js, tests/ui/linkformview.js, theme/components/linkform.scss
…ocused. Closes #90.
Fix: Esc key should close the link panel even if none of the `LinkFormView` fields is focused. Closes #90.
---
Requires https://github.com/ckeditor/ckeditor5-ui/pull/213.
=> t/90: Esc key should close the link panel even if none of the form fields is focused

src/link.js, tests/link.js, tests/manual/tickets/113/1.html, tests/manual/tickets/113/1.js, tests/manual/tickets/113/1.md
Fix: Link balloon should update its position upon external document changes. Closes #113.
=> T/113: Link balloon should update its position upon external document changes

src/ui/linkformview.js, tests/ui/linkformview.js
Feature: URL input field should provide a placeholder. Closes #109.
---
* Requires https://github.com/ckeditor/ckeditor5-ui/pull/221.
=> t/109: URL input field should provide a placeholder

src/link.js, tests/link.js
Fix: The URL field's value should be updated each time the form shows up. Closes #78.
---
Probably also resolves https://github.com/ckeditor/ckeditor5-ui/issues/135.
=> t/78: The URL field's value should be updated each time the form shows up

src/link.js, tests/link.js
Fix: The editing UI should show up when the selection encloses a link. Closes #23.
=> t/23: The editing UI should show up when the selection encloses a link

src/link.js, tests/link.js
Fix: URL input value should not be 'undefined' when no link is selected. Closes #123.
---
A regression after #119.
=> t/123: URL input value should not be 'undefined' when no link is selected

src/link.js, tests/link.js
Fix: Keyboard listener should check if the command is enabled before opening the balloon. Closes #128.
=> t/128: Keyboard listener should check if the command is enabled before opening the balloon

package.json, src/linkcommand.js, tests/integration.js
Fix: Linking an entire image should not be possible. Closes #85.
=> t/85: Linking an image should not be possible

src/link.js, tests/link.js
Feature: Switched `LinkFormView` to the read-only mode when `LinkCommand` and `UnlinkCommand` are disabled. Closes #135.
---
Requires https://github.com/ckeditor/ckeditor5-ui/pull/267.
=> Switched LinkForm to the read-only mode when link and unlink commands are disabled.

src/link.js, tests/link.js
Fix: Unlink button in the balloon should be visible when a link is partially selected. Closes #141.
=> t/141: Unlink button in the balloon should be visible when a link is partially selected

src/link.js, tests/link.js, tests/ui/linkformview.js
Fix: The Link keystrokes should properly integrate with the List feature. Improved balloon positioning. Closes #146.
---
* Requires https://github.com/ckeditor/ckeditor5-core/pull/102.
=> t/ckeditor5/447: The Link keystrokes should properly integrate with the List feature. Improved balloon positioning

src/link.js, tests/link.js, tests/manual/link.js, tests/manual/link.md
Other: Removed the "Unlink" button from the toolbars. Closes #52.
---
Branches in other repositories:
* https://github.com/ckeditor/ckeditor5-block-quote/tree/t/ckeditor5-link/52
* https://github.com/ckeditor/ckeditor5-core/tree/t/ckeditor5-link/52
* https://github.com/ckeditor/ckeditor5-editor-inline/tree/t/ckeditor5-link/52
* https://github.com/ckeditor/ckeditor5-presets/tree/t/ckeditor5-link/52
* https://github.com/ckeditor/ckeditor5-ui/tree/t/ckeditor5-link/52
=> t/52: Removed the "Unlink" button from the toolbars

theme/components/linkform.scss
Fix: The URL input should span the width of the balloon. Closes #145.
---
=> t/145: The URL input should span the width of the balloon

src/link.js, tests/link.js
Fix: Prevented default browser actions on CTRL+K. Closes #153. Closes #154.
=> Prevent default browser actions on CTRL+K

src/linkcommand.js, tests/linkcommand.js
Fix: Link feature was creating empty text nodes with `linkHref` attribute. Closes #169.
=> Link feature was creating empty text nodes with linkHref attribute

src/link.js, tests/link.js
Feature: Added two-step caret movement for `linkHref` attribute. Closes #72.
=> Feature: Enabled two-step caret movement for `linkHref` attribute.

src/ui/linkformview.js
Feature: Made the link form buttons thicker with a fill color and no background (see ckeditor/ckeditor5#810).
---
Requires:
1. https://github.com/ckeditor/ckeditor5-core/pull/125
2. https://github.com/ckeditor/ckeditor5-theme-lark/pull/161
=> t/ckeditor5/810: Made the link form buttons thicker with a fill color and no background.

src/ui/linkformview.js, tests/ui/linkformview.js
Other: Used `.ck-button_save` and `_cancel` CSS classes to make the link form view buttons colorful (see ckeditor/ckeditor5-image#187).
=> t/ckeditor5-image/187: Used .ck-button_save and _cancel CSS classes to make the link form view buttons colorful

src/linkediting.js, tests/linkediting.js, tests/linkui.js
Fix: The selected link should be highlighted using the class instead of a marker. Closes #180. Closes #176. Closes ckeditor/ckeditor5#888.
=> t/180: The selected link should be highlighted using the class instead of a marker.

src/linkui.js, tests/linkui.js
Feature: The Ctrl+K keystroke should open link URL editing dialog. Closes #181.
=> t/181: Feature: The Ctrl+K keystroke should open link URL editing dialog

src/linkui.js, tests/linkui.js
Internal: Added names to the plugins that expose a public API (see ckeditor/ckeditor5#1336).
---
Part of https://github.com/ckeditor/ckeditor5/issues/1336.
=> t/ckeditor5/1336: Added names to the plugins that expose a public API

src/linkui.js, tests/linkui.js
Fix: Improved focus managing before removing the active element from the DOM. Closes https://github.com/ckeditor/ckeditor5/issues/1501.
---
=> Improved focus managing before removing the active element from the DOM

theme/linkactions.css, theme/linkform.css
Other: Aligned import paths after moving `_rwd.css` file from `theme-lark` to `ui`. See ckeditor/ckeditor5#1662.
=> Fix "_rwd.css" import path

src/linkcommand.js, tests/linkcommand.js
Other: `Use model.insertContent` instead of `model.Writer.insert`. Closes #224.
=> Use model.insertContent instead of model.Writer.insert

src/linkui.js, tests/linkui.js
Fix: Link balloon will not be shown if no link was added after command execution. Closes #171.
=> Link balloon will not be shown if no link was added after command execution

src/linkediting.js, tests/linkediting.js, tests/manual/linkdecorator.html, tests/manual/linkdecorator.js, tests/manual/linkdecorator.md
Fix: Provide missing upcast converter for link decorators. Closes #233.
---
=> Provide missing upcast converter for link decorators

docs/_snippets/features/build-link-source.js, docs/_snippets/features/link.js, docs/_snippets/features/linkdecorators.html, docs/_snippets/features/linkdecorators.js, docs/features/link.md, src/link.js
Docs: Documentation for link's decorators. Closes #229.
---
~⚠️ branch target to `t/186` to have available feature to build snippets.~
=> Add documentation for link decorators.

docs/_snippets/features/linkdecorators.html, docs/features/link.md
Docs: Enabled text wrapping to the new line in the decorators demo output. Closes #236.
Docs: Simplified the markup of the decorators demo in the link feature guide. Closes #239.
=> t/236,239: Improvements to the decorators demo

package.json, src/linkui.js, tests/linkui.js
Fix: Improved balloon positioning when there is more than one stack in the rotator. Closes #242.
---
=> Improved balloon positioning when there is more than one stack in the rotator

src/linkediting.js
Fix: Add missing return value for link postfixer. Closes #241.
---
=> Add missing return value for link postfixer

src/linkediting.js, tests/linkediting.js
Other: Passed editor content direction to the `bindTwoStepCaretToAttribute()` helper in the `LinkEditing` plugin. See ckeditor/ckeditor5#1151.
---
A piece of https://github.com/ckeditor/ckeditor5/pull/1881.
=> t/ckeditor5/1151: Passed editor content direction to the bindTwoStepCaretToAttribute() helper in the LinkEditing plugin

src/linkui.js, tests/linkui.js
Fix: Set UI buttons as toggleable.
---
Requires: ckeditor/ckeditor5-ui#517
* There is also change in `isOn` property to have sure that boolean value is kept inside it.
=> Set UI buttons as toggleable

src/ui/linkactionsview.js, tests/ui/linkactionsview.js
Fix: Link preview in the balloon should have `rel="noopener noreferrer"` set for security reasons. Closes ckeditor/ckeditor5#5746.
=> i/5746: Link preview in the balloon should have `rel="noopener noreferrer"`

docs/features/link.md
Fix typo with external links snippet. (`addTargetToLinks` to `addTargetToExternalLinks`)
=> Docs: Fix addTargetToLinks typo

src/linkui.js, tests/linkui.js
Fix: The balloon toolbar will be displayed if a selection is placed inside a link even if the `link` command is disabled. Closes ckeditor/ckeditor5#4834.
=> Toolbar will be displayed even if the command is disabled

src/linkui.js, src/ui/linkformview.js, tests/linkui.js, tests/ui/linkformview.js
Other: Replaced `LabeledInputView` with `LabeledFieldView`. See ckeditor/ckeditor5#6110.
--
Master PR: ckeditor/ckeditor5-theme-lark/pull/274
=> i/6110: Replace LabeledInputView with LabeledFieldView

src/linkui.js, tests/linkui.js
Fix: Get the value of URL from the DOM input element value, instead of the `LinkFormView#urlInputView#fieldView#value` on submit. Closes ckeditor/ckeditor5#6530.
=> i/6530: Get value of the URL from DOM element.value

theme/linkform.css
Fix: Replaced `.ck-labeled-input` class with `.ck-labeled-field-view`. See ckeditor/ckeditor5#6553.
⚠️**Required:** 
---
These changes fix missing styles after merging ckeditor/ckeditor5/issues/6110.
=> i/6553: Replace .ck-labeled-input class with .ck-labeled-field-view

src/linkediting.js, tests/linkediting.js, tests/manual/tickets/6053/1.html, tests/manual/tickets/6053/1.js, tests/manual/tickets/6053/1.md
Fix: Link selection attributes should be cleared after inserting a link via `Model#insertContent()` for better UX. Closes ckeditor/ckeditor5#6053.
---
A new approach to the problem ([the old one](https://github.com/ckeditor/ckeditor5-link/pull/260)) after a F2F talk with @Reinmar. Let's take a look at it and discuss it here.
FYI: I smuggled some async/await refactoring to the LinkEditing tests just like @jodator suggested in the old PR.
=> i/6053b: Link selection attributes should be cleared after inserting a link via `Model#insertContent()` for better UX
